document.write('<div id="main-nav">');
document.write('<div id="menu">');
document.write('<div class="menul">');
document.write('<div class="menur">');
document.write('<ul>');
document.write('<li><a href="index.html"><h3>网站首页</h3></a></li>');	  
document.write('<li><a href="service.html"><h3>服务中心</h3></a></li>');
document.write('<li><a href="news.html"><h3>新闻动态</h3></a></li>');
document.write('<li><a href="online_consultant.html"><h3>在线咨询</h3></a></li>');
document.write('<li><a href="case.html"><h3>成功案例</h3></a></li>');
document.write('<li><a href="help.html"><h3>帮助中心</h3></a></li>');
document.write('</ul>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');